### ISSUE TITLE
Without jquery

### ISSUE THREAD

**Issue by militote** [thany/gdpr-cookie#8]
I wanna use gdpr-cookie. but using a whole library (Jquery) for this is too much

It would be great to use gdpr-cookie in pure javascript

**Comment by thany** [comment]
Thanks for trying it out anyway :)
I understand your concern, but gdpr-cookie is meant and designed as a jQuery plugin. Doing away with that would reduce browser compatibility or inflate the codebase quite a lot, or both. On top of that, jQuery, is still a popular library that gets included anyway on a lot of sites.

So I'm sorry to say that this won't be fixed in the forseeable future. Feel free to make a fork though ;)
